name: ${name}
version: ${version}
description: ${description}

authors: [TheBlockBender, JustDJplease]
main: me.theblockbender.nature.sounds.NatureSounds
website: https://github.com/JustDJplease/NatureSounds
database: false

api-version: 1.13